[package]
name = "tauri-plugin-clipboard"
description = "A clipboard plugin for Tauri that supports both text and image"
license = "MIT"
version = "0.1.0"
authors = [ "You" ]
edition = "2021"
rust-version = "1.59"
exclude = ["/examples", "/webview-dist", "/webview-src", "node_modules"]
repository = "https://github.com/CrossCopy/tauri-plugin-clipboard"

[dependencies]
tauri = { version = "1.2.2" }
serde = "1.0"
thiserror = "1.0"
arboard = "3.2.0"
image = "0.24.5"
tempfile = "3.3.0"
base64 = "0.21.0"
