name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - 'webview-src/**'
      - 'webview-dist/**'
      - 'examples/**'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0

    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=Cargo.toml --release
